/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "inverse-primary": "#b2c5ff",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#c4d2ff",
        "on-tertiary-container": "#c4d4ee",
        "on-tertiary-fixed": "#0b1c30",
        "surface-container": "#eceef0",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "on-secondary-fixed": "#0d1c2f",
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#38485d",
        "on-error": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-tint": "#0c56d0",
        "secondary-fixed": "#d5e3fd",
        "on-primary-fixed": "#001848",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "outline": "#737685",
        "primary-fixed-dim": "#b2c5ff",
        "on-primary-fixed-variant": "#0040a2",
        "secondary-fixed-dim": "#b9c7e0",
        "primary-fixed": "#dae2ff",
        "secondary": "#334155",
        "on-secondary-container": "#57657b",
        "secondary-container": "#d5e3fd",
        "primary-container": "#0052cc",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed-variant": "#3a485c",
        "tertiary": "#64748B",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c3c6d6",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#d3e4fe",
        "on-secondary": "#ffffff",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#b7c8e1",
        "surface-container-low": "#f2f4f6",
        "primary": "#0052cc",
        "tertiary-container": "#4c5c72",
        "on-surface-variant": "#434654",
        "neutral": "#f8fafc"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "margin": "32px",
        "xs": "4px",
        "md": "16px",
        "xl": "32px",
        "base": "8px",
        "2xl": "48px",
        "gutter": "24px",
        "lg": "24px"
      },
      fontFamily: {
        "label-bold": ["Inter"],
        "h1": ["Inter"],
        "body-sm": ["Inter"],
        "h2": ["Inter"],
        "body-md": ["Inter"],
        "h3": ["Inter"],
        "body-lg": ["Inter"],
        "code": ["JetBrains Mono"]
      },
      fontSize: {
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "h1": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "h3": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code": ["13px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
