package com.assettrack.domain;

import java.time.LocalDate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity representing a physical or digital asset tracked by the AssetTrack system.
 *
 * <p>Maps to the {@code assets} table in PostgreSQL. Each asset is uniquely identified by its
 * {@code serialNumber} and progresses through a lifecycle defined by the {@link Status} enum.
 *
 * <p><strong>Database constraints enforced by this mapping:</strong>
 * <ul>
 *     <li>{@code serial_number} — {@code UNIQUE} and {@code NOT NULL}; the natural business key
 *         that distinguishes every physical unit.</li>
 *     <li>{@code status} — Stored as a {@code VARCHAR} via {@code EnumType.STRING} for readability
 *         and safe enum evolution.</li>
 * </ul>
 *
 * @see Status
 */
@Entity
@Table(name = "assets")
public class Asset {

    // ──────────────────────────────────────────────────────────────────────────────
    // Primary Key
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * Surrogate primary key, auto-generated by the database using an identity column.
     * Uses the same {@code IDENTITY} strategy as {@link User} for consistency across the schema.
     * {@code updatable = false} prevents accidental modification after initial persistence.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false)
    private Long id;

    // ──────────────────────────────────────────────────────────────────────────────
    // Descriptive Fields
    // ──────────────────────────────────────────────────────────────────────────────

    /** The category or type of the asset (e.g., "Laptop", "Monitor", "Keyboard"). */
    @Column(name = "type")
    private String type;

    /** The manufacturer or brand of the asset (e.g., "Dell", "Apple", "Lenovo"). */
    @Column(name = "brand")
    private String brand;

    /** The specific model name or number of the asset (e.g., "XPS 15 9530", "MacBook Pro 16"). */
    @Column(name = "model")
    private String model;

    // ──────────────────────────────────────────────────────────────────────────────
    // Identification
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * The manufacturer-assigned serial number of the asset.
     * Marked {@code unique} and {@code nullable = false} because every tracked asset must have
     * a verifiable, one-of-a-kind identifier that prevents duplicate registrations.
     */
    @Column(name = "serial_number", nullable = false, unique = true)
    private String serialNumber;

    // ──────────────────────────────────────────────────────────────────────────────
    // Lifecycle Dates
    // ──────────────────────────────────────────────────────────────────────────────

    /** The date on which the asset was purchased or acquired. */
    @Column(name = "purchase_date")
    private LocalDate purchaseDate;

    /** The date on which the asset's warranty coverage expires. */
    @Column(name = "warranty_expiration_date")
    private LocalDate warrantyExpirationDate;

    // ──────────────────────────────────────────────────────────────────────────────
    // Status
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * The current lifecycle status of the asset.
     * Persisted as a {@code VARCHAR} string (e.g. "AVAILABLE", "ASSIGNED") rather than an ordinal
     * integer, so that column values remain meaningful even if the enum order changes.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status")
    private Status status;

    // ──────────────────────────────────────────────────────────────────────────────
    // Constructors
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * No-argument constructor required by the JPA specification.
     * Frameworks (Hibernate) use this to instantiate entities via reflection.
     */
    public Asset() {
    }

    /**
     * Convenience constructor for creating a fully-populated Asset instance.
     *
     * @param type                   the category of the asset (e.g., "Laptop")
     * @param brand                  the manufacturer or brand
     * @param model                  the specific model name or number
     * @param serialNumber           the unique manufacturer serial number
     * @param purchaseDate           the date the asset was acquired
     * @param warrantyExpirationDate the date the warranty expires
     * @param status                 the initial lifecycle status
     */
    public Asset(String type, String brand, String model, String serialNumber,
                 LocalDate purchaseDate, LocalDate warrantyExpirationDate, Status status) {
        this.type = type;
        this.brand = brand;
        this.model = model;
        this.serialNumber = serialNumber;
        this.purchaseDate = purchaseDate;
        this.warrantyExpirationDate = warrantyExpirationDate;
        this.status = status;
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // Getters & Setters
    // ──────────────────────────────────────────────────────────────────────────────

    public Long getId() {
        return id;
    }

    /**
     * ID is managed by the database identity column and should not normally be set
     * manually. This setter exists for framework compatibility and testing.
     */
    public void setId(Long id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public LocalDate getPurchaseDate() {
        return purchaseDate;
    }

    public void setPurchaseDate(LocalDate purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    public LocalDate getWarrantyExpirationDate() {
        return warrantyExpirationDate;
    }

    public void setWarrantyExpirationDate(LocalDate warrantyExpirationDate) {
        this.warrantyExpirationDate = warrantyExpirationDate;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // Object Overrides
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * Returns a human-readable representation of this asset,
     * useful for debugging and logging.
     */
    @Override
    public String toString() {
        return "Asset{" +
                "id=" + id +
                ", type='" + type + '\'' +
                ", brand='" + brand + '\'' +
                ", model='" + model + '\'' +
                ", serialNumber='" + serialNumber + '\'' +
                ", purchaseDate=" + purchaseDate +
                ", warrantyExpirationDate=" + warrantyExpirationDate +
                ", status=" + status +
                '}';
    }
}
