package com.assettrack.domain;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity representing a registered user of the AssetTrack system.
 *
 * <p>Maps to the {@code users} table in PostgreSQL. Each user has a unique email
 * address used as the login credential, a BCrypt-hashed password, and an assigned
 * {@link Role} that governs their authorization level.
 *
 * <p><strong>Database constraints enforced by this mapping:</strong>
 * <ul>
 *     <li>{@code email} — {@code UNIQUE} and {@code NOT NULL}; serves as the natural business key.</li>
 *     <li>{@code password} — {@code NOT NULL}; always stores a BCrypt hash, never plaintext.</li>
 *     <li>{@code role} — Stored as a {@code VARCHAR} via {@code EnumType.STRING} for readability.</li>
 * </ul>
 *
 * @see Role
 */
@Entity
@Table(name = "users") // "user" is a reserved keyword in PostgreSQL; use "users" instead.
public class User {

    // ──────────────────────────────────────────────────────────────────────────────
    // Primary Key
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * Surrogate primary key, auto-generated by the database using an identity column.
     * {@code updatable = false} prevents accidental modification after initial persistence.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", updatable = false)
    private Long id;

    // ──────────────────────────────────────────────────────────────────────────────
    // Authentication Fields
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * The user's email address — used as the unique login identifier.
     * Marked {@code unique} and {@code nullable = false} to enforce a one-account-per-email policy
     * at the database level, complementing any application-layer validation.
     */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /**
     * The user's password stored as a BCrypt hash.
     * Marked {@code nullable = false} because every account must have a password.
     * <strong>Must never contain plaintext</strong> — the service layer is responsible
     * for hashing before persistence.
     */
    @Column(name = "password", nullable = false)
    private String password;

    // ──────────────────────────────────────────────────────────────────────────────
    // Profile Fields
    // ──────────────────────────────────────────────────────────────────────────────

    /** The user's first (given) name. */
    @Column(name = "first_name")
    private String firstName;

    /** The user's last (family) name. */
    @Column(name = "last_name")
    private String lastName;

    // ──────────────────────────────────────────────────────────────────────────────
    // Authorization
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * The authorization role assigned to this user.
     * Persisted as a {@code VARCHAR} string (e.g. "ADMIN", "MANAGER", "DEVELOPER") rather than
     * an ordinal integer, so that column values remain meaningful even if the enum order changes.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role")
    private Role role;

    // ──────────────────────────────────────────────────────────────────────────────
    // Constructors
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * No-argument constructor required by the JPA specification.
     * Frameworks (Hibernate) use this to instantiate entities via reflection.
     */
    public User() {
    }

    /**
     * Convenience constructor for creating a fully-populated User instance.
     *
     * @param email     the user's unique email address
     * @param password  the BCrypt-hashed password
     * @param firstName the user's first name
     * @param lastName  the user's last name
     * @param role      the authorization role assigned to this user
     */
    public User(String email, String password, String firstName, String lastName, Role role) {
        this.email = email;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.role = role;
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // Getters & Setters
    // ──────────────────────────────────────────────────────────────────────────────

    public Long getId() {
        return id;
    }

    /**
     * ID is managed by the database identity column and should not normally be set
     * manually. This setter exists for framework compatibility and testing.
     */
    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    // ──────────────────────────────────────────────────────────────────────────────
    // Object Overrides
    // ──────────────────────────────────────────────────────────────────────────────

    /**
     * Returns a human-readable representation of this user.
     * The password field is intentionally excluded to prevent accidental logging of secrets.
     */
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", role=" + role +
                '}';
    }
}
