spring.application.name=asset-track-management-API

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/assettrack-db
spring.datasource.username=assettrack-user
spring.datasource.password=admin12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true